Repository saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE, pull requests merged in 2024-10, with the labels that each got.

#89 Added X logo
  package-lock.json
  package.json
  src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, Level-1, hacktoberfest

#125 Added logout function to the website
  backend/api/controllers/userController.js
  backend/api/routes/userRoute.js
  backend/server.js
  src/App.js
  src/api/endPoints.js
  src/components/ContactUs.jsx
  src/components/FAQ.jsx
  src/components/Navbar.jsx
  src/index.js
  src/pages/ContactUsPage.jsx
  src/pages/Home.jsx
  src/services/userAPI/signInAPI.js
  src/store/store.js
Labels: gssoc-ext, hacktoberfest-accepted, Level3, hacktoberfest

#184 Added the Contributors Page in the website.
  public/index.html
  src/App.js
  src/components/Footer.jsx
  src/data.js
  src/pages/ContributorsPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#239 fix 216,219,221
  src/pages/Login.jsx
  src/pages/Register.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest
